export const studenthubRoute = '/student-hub'
export const aboutRoute = '/about'
export const applicationRoute = '/application'
export const contactRoute = '/contact'
export const eventsRoute = '/events'
export const homeRoute = '/'
export const whatsappCommunityRoute= 'https://chat.whatsapp.com/BId8WxG1c0B2DlJ6Oz1Fb5'